server:
  port: 8090
spring:
  thymeleaf:
    cache: false
    prefix: C:\Users\enter\IdeaProjects\chat\src\main\resources
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true